from datetime import datetime, timezone
import re
import secrets
import string

from sqlalchemy import and_, delete, func, or_, select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session, selectinload

from core.password_policy import validate_password
from core.permissions import invalidate_permission_cache
from core.security import hash_password
from modules.approvals.model import ApprovalRequest, ApprovalTask, TaskAuditLog
from modules.errors import NotFoundError, RbacSafetyError
from modules.org_units.model import OrgUnit
from modules.rbac_association import user_org_unit
from modules.rbac_audit.service import RbacAuditService
from modules.rbac_safety import (
    assert_did_not_remove_last_role_based_admin,
    assert_self_role_assign_keeps_users_view,
    assert_self_role_ids_replacement_keeps_users_view,
    count_superusers,
    count_users_with_admin_capability,
)
from modules.rbac_versioning.service import bump_user_permission_version
from modules.roles.model import Role
from modules.users.model import User
from modules.users.schema import UserCreate, UserUpdate
from modules.approvals.assignment_service import get_workflow_for_action
from modules.approvals.service import ApprovalEngineService
from modules.mfa.policy_hooks import maybe_send_mfa_setup_for_user
from modules.mfa.notify import create_mfa_setup_link
from modules.emails.service import EmailNotificationService
from modules.auth_policy.service import get_global_policy


class DuplicateEmailError(Exception):
    """Another user already owns this email address."""


class DuplicatePhoneError(Exception):
    """Another user already owns this phone number."""

class DuplicateUsernameError(Exception):
    """Another user already owns this username."""

class DuplicateEmployeeCodeError(Exception):
    """Another user already owns this employee code."""


class UserService:
    def __init__(self, db: Session) -> None:
        self._db = db

    @staticmethod
    def _normalize_phone(phone: str) -> str:
        normalized = phone.strip()
        if not re.fullmatch(r"[6-9]\d{9}", normalized):
            raise ValueError("Phone must start with 6, 7, 8, or 9 and be exactly 10 digits")
        return normalized

    @staticmethod
    def _generate_password() -> str:
        alphabet = string.ascii_letters + string.digits + "!@#$%^&*()-_=+[]{}"
        return "".join(secrets.choice(alphabet) for _ in range(20))

    @staticmethod
    def _normalize_employee_code(employee_code: str | None) -> str | None:
        if employee_code is None:
            return None
        normalized = str(employee_code).strip().upper()
        return normalized or None

    def _find_existing_employee_code_user_id(
        self,
        employee_code: str | None,
        *,
        exclude_user_id: int | None = None,
    ) -> int | None:
        normalized = self._normalize_employee_code(employee_code)
        if not normalized:
            return None
        stmt = select(User.id).where(func.upper(func.btrim(User.employee_code)) == normalized)
        if exclude_user_id is not None:
            stmt = stmt.where(User.id != int(exclude_user_id))
        return self._db.scalar(stmt)

    def create_user(self, data: UserCreate, *, actor_user_id: int | None = None) -> User:
        phone = self._normalize_phone(data.phone)
        requested_active = bool(data.is_active)
        existing_phone = self._db.scalar(select(User.id).where(User.phone == phone))
        if existing_phone is not None:
            raise DuplicatePhoneError

        username_norm = str(data.username).strip()
        if not username_norm:
            raise ValueError("Username is required")
        existing_username = self._db.scalar(select(User.id).where(User.username == username_norm))
        if existing_username is not None:
            raise DuplicateUsernameError

        email_norm = data.email.lower().strip()
        existing_email = self._db.scalar(select(User.id).where(User.email == email_norm))
        if existing_email is not None:
            raise DuplicateEmailError

        employee_code_norm = self._normalize_employee_code(getattr(data, "employee_code", None))
        if self._find_existing_employee_code_user_id(employee_code_norm) is not None:
            raise DuplicateEmployeeCodeError

        resolved_role_ids = list(data.role_ids or [])
        if not resolved_role_ids:
            raise ValueError("Provide role_id or role_ids with at least one role")
        roles: list[Role] = []
        for rid in resolved_role_ids:
            role = self._db.get(Role, int(rid))
            if role is None:
                raise NotFoundError("Role", int(rid))
            roles.append(role)

        org = self._db.get(OrgUnit, data.org_unit_id)
        if org is None:
            raise NotFoundError("OrgUnit", data.org_unit_id)

        autogenerated = True
        plain_password = self._generate_password()
        validate_password(plain_password)

        now = datetime.now(timezone.utc)
        user = User(
            full_name=data.full_name.strip(),
            username=username_norm,
            phone=phone,
            email=email_norm,
            employee_code=employee_code_norm,
            department=str(data.department).strip() if getattr(data, "department", None) else None,
            designation=str(data.designation).strip() if getattr(data, "designation", None) else None,
            address=str(data.address) if getattr(data, "address", None) else None,
            hashed_password=hash_password(plain_password),
            password_changed_at=now,
            is_active=requested_active,
        )
        for role in roles:
            user.roles.append(role)
        self._db.add(user)
        self._db.flush()

        self._db.execute(
            delete(user_org_unit).where(user_org_unit.c.user_id == user.id)
        )
        self._db.execute(
            user_org_unit.insert().values(user_id=user.id, org_unit_id=org.id)
        )

        audit = RbacAuditService(self._db)
        audit.log(
            actor_user_id=actor_user_id,
            target_type="user",
            target_id=user.id,
            action="assign",
            old_value=None,
            new_value={"role_ids": [int(r.id) for r in roles], "role_names": [r.name for r in roles]},
        )
        bump_user_permission_version(self._db, user.id)

        # Approval: resolve workflow by RBAC action code (``users.create``), with legacy
        # ``entity_type=user_creation`` fallback when no mapping exists.
        wf = get_workflow_for_action(self._db, "users.create")
        if wf is not None:
            user.is_active = False
            ApprovalEngineService(self._db).create_request_for_entity(
                workflow=wf,
                entity_type="user_creation",
                entity_id=user.id,
                payload={
                    "action_code": "users.create",
                    "full_name": user.full_name,
                    "username": user.username,
                    "phone": user.phone,
                    "email": user.email,
                    "role_id": int(roles[0].id),
                    "role_ids": [int(r.id) for r in roles],
                    "org_unit_id": org.id,
                    "is_active": requested_active,
                    # If MFA is enforced, setup email will be sent after approval anyway.
                    # We keep the temporary password so it can be emailed after approval.
                    "temp_password": plain_password if autogenerated else None,
                },
                created_by=actor_user_id,
            )

        try:
            self._db.commit()
        except IntegrityError:
            self._db.rollback()
            # Most likely duplicate phone/email race.
            if self._db.scalar(select(User.id).where(User.phone == phone)) is not None:
                raise DuplicatePhoneError from None
            if self._db.scalar(select(User.id).where(User.username == username_norm)) is not None:
                raise DuplicateUsernameError from None
            if email_norm and self._db.scalar(select(User.id).where(User.email == email_norm)) is not None:
                raise DuplicateEmailError from None
            if self._find_existing_employee_code_user_id(employee_code_norm) is not None:
                raise DuplicateEmployeeCodeError from None
            raise
        user_id = user.id
        self._db.expire_all()
        reloaded = self._db.scalar(
            select(User)
            .where(User.id == user_id)
            .options(
                selectinload(User.roles),
                selectinload(User.org_units),
                selectinload(User.mfa_record),
            )
        )
        assert reloaded is not None
        if reloaded.is_active and wf is None:
            # No approval workflow → user is active immediately.
            # If password was auto-generated, email it with USER_CREATED.
            if autogenerated and reloaded.email:
                EmailNotificationService(self._db).trigger_event(
                    event_code="USER_CREATED",
                    payload={
                        "user_name": reloaded.full_name,
                        "username": reloaded.username,
                        "email": reloaded.email,
                        "company_name": "Ultra Workspace",
                        "temp_password": plain_password,
                    },
                )
            maybe_send_mfa_setup_for_user(self._db, reloaded)
        return reloaded

    def list_users(self, *, offset: int = 0, limit: int = 50) -> list[User]:
        stmt = (
            select(User)
            .options(selectinload(User.roles), selectinload(User.org_units), selectinload(User.mfa_record))
            .order_by(User.created_at.desc())
            .offset(offset)
            .limit(limit)
        )
        return list(self._db.scalars(stmt).all())

    def count_users(self) -> int:
        return int(self._db.scalar(select(func.count()).select_from(User)) or 0)

    def update_user(
        self,
        user_id: int,
        data: UserUpdate,
        *,
        actor_user_id: int | None = None,
    ) -> User:
        admin_before = count_users_with_admin_capability(self._db)
        user = self._db.get(User, user_id)
        if user is None:
            raise NotFoundError("User", user_id)
        if user.is_superuser:
            raise ValueError("Cannot modify superuser via admin user management")

        updates = data.model_dump(exclude_unset=True)

        before_snapshot = {
            "full_name": user.full_name,
            "username": user.username,
            "phone": user.phone,
            "email": user.email,
            "employee_code": user.employee_code,
            "is_active": bool(user.is_active),
        }

        if "full_name" in updates and updates["full_name"] is not None:
            user.full_name = str(updates["full_name"]).strip()

        if "username" in updates and updates["username"] is not None:
            uname = str(updates["username"]).strip()
            if not uname:
                raise ValueError("Username is required")
            existing = self._db.scalar(select(User.id).where(User.username == uname, User.id != user.id))
            if existing is not None:
                raise DuplicateUsernameError
            user.username = uname

        if "phone" in updates and updates["phone"] is not None:
            phone = self._normalize_phone(str(updates["phone"]))
            existing = self._db.scalar(select(User.id).where(User.phone == phone, User.id != user.id))
            if existing is not None:
                raise DuplicatePhoneError
            user.phone = phone

        if "email" in updates:
            email_val = updates["email"]
            email_norm = email_val.lower().strip() if email_val is not None else None
            if email_norm:
                existing = self._db.scalar(
                    select(User.id).where(User.email == email_norm, User.id != user.id)
                )
                if existing is not None:
                    raise DuplicateEmailError
            user.email = email_norm

        if "employee_code" in updates:
            emp = self._normalize_employee_code(updates["employee_code"])
            if emp and self._find_existing_employee_code_user_id(emp, exclude_user_id=user.id) is not None:
                raise DuplicateEmployeeCodeError
            user.employee_code = emp
        if "department" in updates:
            user.department = str(updates["department"]).strip() if updates["department"] else None
        if "designation" in updates:
            user.designation = str(updates["designation"]).strip() if updates["designation"] else None
        if "address" in updates:
            user.address = str(updates["address"]) if updates["address"] else None

        # Password updates intentionally removed from admin UI flow.

        if "is_active" in updates and updates["is_active"] is not None:
            user.is_active = bool(updates["is_active"])

        role_changed = False
        new_role_ids: list[int] | None = None
        if "role_ids" in updates and updates["role_ids"] is not None:
            new_role_ids = sorted({int(x) for x in updates["role_ids"] if int(x) >= 1})
        elif "role_id" in updates and updates["role_id"] is not None:
            new_role_ids = [int(updates["role_id"])]

        if new_role_ids is not None:
            if not new_role_ids:
                raise ValueError("At least one role is required")
            old_ids = sorted({r.id for r in user.roles})
            assert_self_role_ids_replacement_keeps_users_view(
                self._db,
                actor_user_id=actor_user_id,
                target_user_id=user_id,
                new_role_ids=new_role_ids,
            )
            roles: list[Role] = []
            for rid in new_role_ids:
                role = self._db.get(Role, int(rid))
                if role is None:
                    raise NotFoundError("Role", int(rid))
                roles.append(role)
            user.roles.clear()
            for role in roles:
                user.roles.append(role)
            role_changed = True
            audit = RbacAuditService(self._db)
            audit.log(
                actor_user_id=actor_user_id,
                target_type="user",
                target_id=user_id,
                action="update",
                old_value={"role_ids": old_ids},
                new_value={
                    "role_ids": [int(r.id) for r in roles],
                    "role_names": [r.name for r in roles],
                },
            )

        if "org_unit_id" in updates and updates["org_unit_id"] is not None:
            org = self._db.get(OrgUnit, int(updates["org_unit_id"]))
            if org is None:
                raise NotFoundError("OrgUnit", int(updates["org_unit_id"]))
            self._db.execute(delete(user_org_unit).where(user_org_unit.c.user_id == user.id))
            self._db.execute(
                user_org_unit.insert().values(user_id=user.id, org_unit_id=org.id)
            )

        self._db.flush()
        assert_did_not_remove_last_role_based_admin(
            self._db, admin_capable_users_before=admin_before
        )

        if role_changed:
            bump_user_permission_version(self._db, user_id)

        try:
            self._db.commit()
        except IntegrityError:
            self._db.rollback()
            if "phone" in updates and user.phone and self._db.scalar(select(User.id).where(User.phone == user.phone, User.id != user.id)) is not None:
                raise DuplicatePhoneError from None
            if "username" in updates and user.username and self._db.scalar(select(User.id).where(User.username == user.username, User.id != user.id)) is not None:
                raise DuplicateUsernameError from None
            if "email" in updates and user.email and self._db.scalar(select(User.id).where(User.email == user.email, User.id != user.id)) is not None:
                raise DuplicateEmailError from None
            if self._find_existing_employee_code_user_id(user.employee_code, exclude_user_id=user.id) is not None:
                raise DuplicateEmployeeCodeError from None
            raise

        uid = user.id
        self._db.expire_all()
        reloaded = self._db.scalar(
            select(User)
            .where(User.id == uid)
            .options(selectinload(User.roles), selectinload(User.org_units), selectinload(User.mfa_record))
        )
        assert reloaded is not None

        after_snapshot = {
            "full_name": reloaded.full_name,
            "username": reloaded.username,
            "phone": reloaded.phone,
            "email": reloaded.email,
            "employee_code": reloaded.employee_code,
            "is_active": bool(reloaded.is_active),
        }
        changed = {k: after_snapshot[k] for k in after_snapshot.keys() if before_snapshot.get(k) != after_snapshot.get(k)}
        if changed:
            try:
                # If this user has an approval request in rework, attach the change audit to the open rework task.
                req = self._db.scalar(
                    select(ApprovalRequest)
                    .where(
                        ApprovalRequest.entity_type == "user_creation",
                        ApprovalRequest.entity_id == int(user_id),
                        ApprovalRequest.status.in_(("in_rework", "rejected")),
                    )
                    .order_by(ApprovalRequest.id.desc())
                    .limit(1)
                )
                if req is not None:
                    rework_task_id = self._db.scalar(
                        select(ApprovalTask.id).where(
                            ApprovalTask.request_id == req.id,
                            ApprovalTask.task_type == "rework",
                            ApprovalTask.status.in_(("open", "pending")),
                        )
                    )
                    if rework_task_id is not None:
                        self._db.add(
                            TaskAuditLog(
                                task_id=int(rework_task_id),
                                action="entity_updated",
                                actor_user_id=actor_user_id,
                                old_value=before_snapshot,
                                new_value=after_snapshot,
                            )
                        )
                        self._db.commit()

                    # Auto-resubmit when the submitter saves changes during rework.
                    if req.created_by is not None and actor_user_id is not None and int(req.created_by) == int(actor_user_id):
                        from modules.approvals.service import ApprovalEngineService

                        ApprovalEngineService(self._db).resubmit_rejected_request(
                            request_id=int(req.id),
                            actor_user_id=int(actor_user_id),
                        )
            except Exception:
                self._db.rollback()
        return reloaded

    def assign_role(
        self,
        user_id: int,
        role_id: int,
        *,
        actor_user_id: int | None = None,
    ) -> None:
        user = self._db.get(User, user_id)
        if user is None:
            raise NotFoundError("User", user_id)
        role = self._db.get(Role, role_id)
        if role is None:
            raise NotFoundError("Role", role_id)
        if role in user.roles:
            return
        assert_self_role_assign_keeps_users_view(
            self._db,
            actor_user_id=actor_user_id,
            target_user_id=user_id,
            role_id=role_id,
        )
        old_ids = sorted({r.id for r in user.roles})
        user.roles.append(role)
        audit = RbacAuditService(self._db)
        audit.log(
            actor_user_id=actor_user_id,
            target_type="user",
            target_id=user_id,
            action="assign",
            old_value={"role_ids": old_ids},
            new_value={"role_ids": old_ids + [role_id]},
        )
        bump_user_permission_version(self._db, user_id)
        try:
            self._db.commit()
        except IntegrityError:
            self._db.rollback()

    def delete_user_permanently(
        self,
        user_id: int,
        *,
        actor_user_id: int | None = None,
    ) -> None:
        """
        Hard-delete a user and remove approval / unified-task data tied to that person.

        Superuser-only at the API layer. Blocks deleting the last superuser and the
        last role-based admin when no other superuser exists (see ``rbac_safety``).
        """
        if actor_user_id is not None and actor_user_id == user_id:
            raise ValueError("You cannot delete your own account from this screen.")

        admin_before = count_users_with_admin_capability(self._db)
        user = self._db.get(User, user_id)
        if user is None:
            raise NotFoundError("User", user_id)

        if user.is_superuser and count_superusers(self._db) <= 1:
            raise RbacSafetyError("Cannot delete the only remaining superuser account.")

        # Pending / historical approval for user onboarding (and any straggler same-entity requests).
        self._db.execute(
            delete(ApprovalRequest).where(
                ApprovalRequest.entity_type == "user_creation",
                ApprovalRequest.entity_id == user_id,
            )
        )

        # Unified / manual tasks that reference this user (tasks linked to requests were CASCADE-deleted).
        self._db.execute(
            delete(ApprovalTask).where(
                or_(
                    and_(ApprovalTask.entity_type == "user_creation", ApprovalTask.entity_id == user_id),
                    ApprovalTask.created_by == user_id,
                    ApprovalTask.assigned_to_user_id == user_id,
                    ApprovalTask.assigned_user_id == user_id,
                )
            )
        )

        # Do not pre-delete user_org_units rows: User.org_units is a secondary association and
        # SQLAlchemy will emit those deletes; pre-deleting causes StaleDataError ("expected 1 row").
        # Foreign keys on user_org_units.user_id use ON DELETE CASCADE, so the row vanishes with the user.
        self._db.delete(user)
        self._db.flush()
        try:
            assert_did_not_remove_last_role_based_admin(
                self._db, admin_capable_users_before=admin_before
            )
            self._db.commit()
        except RbacSafetyError:
            self._db.rollback()
            raise
        except IntegrityError:
            self._db.rollback()
            raise

        invalidate_permission_cache(user_id)

    def resend_mfa_setup_email(self, user_id: int) -> None:
        from modules.mfa.notify import trigger_mfa_setup_email, user_has_pending_user_creation_approval

        user = self._db.scalar(
            select(User)
            .where(User.id == int(user_id))
            .options(selectinload(User.org_units), selectinload(User.mfa_record))
        )
        if user is None:
            raise NotFoundError("User", user_id)
        if not user.is_active:
            raise ValueError("User is not active")
        if user.is_superuser:
            raise ValueError("Not applicable for superuser")
        pol = get_global_policy(self._db)
        if not bool(pol.mfa_enabled):
            raise ValueError("MFA is not enabled")
        if user.mfa_record is not None and bool(user.mfa_record.setup_completed):
            raise ValueError("MFA is already set up")
        if user_has_pending_user_creation_approval(self._db, int(user.id)):
            raise ValueError("User creation approval is still pending")
        trigger_mfa_setup_email(self._db, user, "MFA_SETUP_REMINDER")

    def resend_welcome_email(self, user_id: int) -> None:
        """
        Re-send the final welcome email (USER_CREATED) for an already-approved user.

        Includes:
        - temp password if stored on the last user_creation approval payload (when auto-generated)
        - MFA setup link when policy requires MFA and setup isn't complete
        """
        user = self._db.scalar(
            select(User)
            .where(User.id == int(user_id))
            .options(selectinload(User.org_units), selectinload(User.mfa_record))
        )
        if user is None:
            raise NotFoundError("User", user_id)
        if not user.is_active:
            raise ValueError("User is not active")
        if user.is_superuser:
            raise ValueError("Not applicable for superuser")
        if not user.email:
            raise ValueError("User has no email address")

        payload: dict[str, object] = {
            "user_name": user.full_name,
            "username": user.username,
            "email": user.email,
            "company_name": "Ultra Workspace",
            # keep template variables always present
            "temp_password": "",
            "setup_link": "",
        }

        # Pull temp_password from latest user_creation approval request if available.
        req = self._db.scalar(
            select(ApprovalRequest)
            .where(
                ApprovalRequest.entity_type == "user_creation",
                ApprovalRequest.entity_id == int(user.id),
            )
            .order_by(ApprovalRequest.id.desc())
            .limit(1)
        )
        if req is not None and isinstance(req.payload, dict):
            raw = req.payload.get("temp_password")
            if isinstance(raw, str) and raw.strip():
                payload["temp_password"] = raw.strip()
        # If we no longer have the original temp password (common after older records or manual edits),
        # generate a new temporary password, update the user's credential, and send that.
        if not str(payload.get("temp_password") or "").strip():
            plain = self._generate_password()
            validate_password(plain)
            user.hashed_password = hash_password(plain)
            user.password_changed_at = datetime.now(timezone.utc)
            # Best-effort: keep it on the latest request payload too, so subsequent resends are stable.
            if req is not None and isinstance(req.payload, dict):
                req.payload["temp_password"] = plain
            self._db.commit()
            payload["temp_password"] = plain

        # If MFA is enabled and not completed, include a fresh setup link.
        try:
            pol = get_global_policy(self._db)
            if bool(pol.mfa_enabled) and (user.mfa_record is None or not bool(user.mfa_record.setup_completed)):
                link = create_mfa_setup_link(self._db, user=user)
                if link:
                    payload["setup_link"] = link
        except Exception:
            pass

        EmailNotificationService(self._db).trigger_event(
            event_code="USER_CREATED",
            payload=payload,  # type: ignore[arg-type]
        )
